### ISSUE TITLE
PMBOK - Gerenciamento de riscos

### ISSUE THREAD

**Issue by joaovitorml** [octa-bit/ForceGamaAttack#16]
### Descrição

Elaborar um documento que descreva os processos relacionados ao gerenciamento dos riscos do projeto, garatindo uma chance maior de sucesso do mesmo.

### Tarefas

- [x] Descrever as etapas necessárias para o gerenciamento dos riscos
- [x] Construir a matriz de probabilidade e impacto

### Critérios de aceitação

- [x] Documento ser coerente com o restante do projeto

**Comment by filipetoyoshima** [comment]
Ué, tá feito?

**Comment by joaovitorml** [comment]
Falta adicionar no github pages

**Comment by Eduardolimr** [comment]
Tinha feito direto na wiki, pages ainda estava terminando de configurar.
