### ISSUE TITLE
PMBOK - Gerenciamento de custo

### ISSUE THREAD

**Issue by joaovitorml** [octa-bit/ForceGamaAttack#2]
### Descrição

Elaborar um documento que descreva os processos que estejam relacionados aos custos necessários para a conclusão do projeto.

### Tarefas

- [x] Planejar o gerenciamento dos custos
- [x] Estimar os custos e determinar o orçamento
- [x] Controlar os custos

### Critérios de aceitação

- [x] Orçamento com equipamento e transporte ser dentro do possível para a equipe

**Comment by filipetoyoshima** [comment]
I've posted the doc: https://octa-bit.github.io/ForceGamaAttack/cost.html
