### ISSUE TITLE
Modelo de Domínio

### ISSUE THREAD

**Issue by joaovitorml** [octa-bit/ForceGamaAttack#21]
### Descrição:
Elaborar Modelo de Domínio para construir os objetos necessários para o projeto.

### Tarefas

- [x] Criar o Modelo de Domínio

### Critérios de Aceitação

- [ ] Documento deve ser coerente com o restante do projeto
- [x] Documento deve ser adicionado a Wiki

**Comment by Lucas362** [comment]
Há uma mistura entre inglês e português no documento.

**Comment by isaacborges** [comment]
O mesmo foi validado pela professora. Se acharem necessário, padronizo a linguagem

**Comment by Lucas362** [comment]
Bem, caso tenha sido validado, então acredito não ter problema quanto a padronização, vou considerar a issue como fechada. Vlws
