### ISSUE TITLE
Diagrama de Colaboração

### ISSUE THREAD

**Issue by jlucassr** [octa-bit/ForceGamaAttack#22]
### Descrição:
Elaborar Diagramas de Colaboração para representar a colaboração dinâmica entre os objetos do jogo.

### Tarefas

- [x] Criar diagrama de colaboração do Projeto
- [x] Adicionar o diagrama já criado a Wiki do Pages

### Critérios de Aceitação

- [x] Diagrama de colaboração deve ser coerente com o restante do projeto
- [x] O Diagrama deve estar devidamente na página do Pages

**Comment by Lucas362** [comment]
O tópico Diagrama Sprite na versão 0.2 está vazio

**Comment by isaacborges** [comment]
Sprite na versão 0.2 adicionado

**Comment by jlucassr** [comment]
Diagrama adicionado.
