### ISSUE TITLE
NFR/iStar

### ISSUE THREAD

**Issue by joaovitorml** [octa-bit/ForceGamaAttack#24]
### Descrição:
Elaborar NFR e iStar para englobar requisitos não-funcionais ao escopo do projeto.

### Tarefas

- [ ] Criar NFR
- [ ] Criar iStar

### Critérios de Aceitação

- [ ] Documentos devem ser coerentes com o restante do projeto
- [ ] Documentos deve ser adicionados a Wiki

**Comment by jlucassr** [comment]
Não serão criados artefatos do tipo.
