### ISSUE TITLE
US010 - HUD Básico

### ISSUE THREAD

**Issue by rossicler** [octa-bit/ForceGamaAttack#44]
### Descrição:
**Eu, como**  jogador, **desejo** ver os meus pontos e a quantidade de vida da nave  **para** saber a quantidade de pontos ganho até o momento e a quantidade de vida atual .

#### Critérios de Aceitação:
- [x] Mostrar os pontos obtidos na fase de modo dinâmico.
- [x] Mostrar a vida atual de modo dinâmico.

#### Tarefas:
- [x] Mostrar os pontos na parte superior direita da tela.
- [x] Mostrar a vida atual e vida máxima na parte superior esquerda da tela.
- [x] Fazer com que os pontos sejam atualizados quando um inimigo for morto.
- [x] Fazer com que a vida do usuário seja reduzida após dano.

**Comment by jlucassr** [comment]
HUD foi criado, tudo certo!
