### ISSUE TITLE
US013 - Criar tela de Configurações

### ISSUE THREAD

**Issue by rossicler** [octa-bit/ForceGamaAttack#47]
### Descrição:
**Eu, como**  jogador, **desejo** ver a tela de configurações.

#### Critérios de Aceitação:
- [x] Mostrar as opções de configurações do projeto.

#### Tarefas:
- [x] Após clicar Enter na opção de configurações do menu principal, abrir nova tela.
- [x] Adicionar as opções do projeto na tela.

**Comment by jlucassr** [comment]
Tela foi criada.
