### ISSUE TITLE
Documento de Arquitetura

### ISSUE THREAD

**Issue by joaovitorml** [octa-bit/ForceGamaAttack#52]
### Descrição:
Elaborar o Documento de Arquitetura para definir os componentes do sistema

#### Critérios de Aceitação:
- [x] Documento é coerente com o restante do trabalho
- [x] Contém referencial teórico

#### Tarefas:
- [x] Criar esqueleto do documento

**Comment by jlucassr** [comment]
Documento criado e adicionado na Pages.
